# Generated by Django 4.2.2 on 2023-07-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelname', models.CharField(max_length=100)),
                ('videoName', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
            ],
        ),
    ]
